name: Build Docker Image and Push to Registry

on:
  push:
    tags:
      - v*

jobs:
  main:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest # x64
          - os: ubuntu-24.04-arm # arm64
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      # Remove `v` prefix from tag
      - name: Get version from tag
        id: ver
        run: |
          TAG=${{ github.ref_name }}
          echo "version=${TAG#v}" >> $GITHUB_OUTPUT

      # Login to GitHub Package Registry
      - name: Login to GitHub Package Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push
      - name: Build and push image
        run: |
          docker build . -t ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ steps.ver.outputs.version }} -t ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ steps.ver.outputs.version }}
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
